server:
  port: 7200
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: dm-item-consumer
  rabbitmq:
    host: 192.168.9.151
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 192.168.9.151
    port: 6379
    user: root
    password: 123456
    timeout: 3000
  sleuth:
    sampler:
      percentage: 1.0
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  kafka:
    producer:
      retries: 0
      #batch-size: 16384 # 每次批量发送消息的数量
      bootstrap-servers: 192.168.9.151:9092
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 指定消息key和消息体的编解码方式
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer #添加
    consumer:
      bootstrap-servers: 192.168.9.151:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-consumer-group
      auto-commit-interval: 100
      auto-offset-reset: earliest
      enable-auto-commit: true
    listener:
      poll-timeout: 10000
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@192.168.9.151:7776/eureka/
#      defaultZone: http://root:123456@discovery:9000/eureka/
#      defaultZone: http://root:123456@localhost:9000/eureka/
# dm-goods-provider.ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
hystrix:
  command:
    defalut:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000
ribbon:
  ReadTimeout: 200000
  ConnectTimeout: 200000
logging:
  level: debug

feign:
  hystrix:
    enabled: false #禁用容错处理

moduleName: dm-item